### ISSUE TITLE
[Question] How to install?

### ISSUE THREAD

**Issue by borkmaster12** [PGGB/DeviceChangeFix#1]
I'd like to test this plugin out. What are the steps to install it?

**Comment by PGGB** [comment]
I've submitted it to the Dalamud plugin repository via this PR: https://github.com/goatcorp/DalamudPlugins/pull/1774

Once it is merged you will be able to install it using the FFXIVQuickLauncher. It will be a testing release at first so you will have to enable plugin testing builds: https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-enable-plugin-test-builds

**Comment by PGGB** [comment]
It is available as a testing release in XIVLauncher now.

**Comment by borkmaster12** [comment]
Thank you
