### ISSUE TITLE
When device changes occur, whole game freezes temporarily

### ISSUE THREAD

**Issue by Astariz** [PGGB/DeviceChangeFix#3]
control: When the plugin is disabled and a device change happens (ex keyboard is plugged in), I lose controller functionality for about 5 minutes. Game goes back to normal.

variable: When the plugin is enabled and a device change happens (ex keyboard is plugged in), the whole game freezes for about the same duration. 50% chance controller function comes back. If it doesn't, I need reload the game. Some players have mentioned that my character displays the "disconnected" nameplate icon.

**Comment by l3091** [comment]
having this issue
