### ISSUE TITLE
Dalamud API6 update blocked the plugin

### ISSUE THREAD

**Issue by KellyColt** [PGGB/DeviceChangeFix#4]
This got disabled with the new update for compatibility with ff14v6.1 
Since I couldn't find any info whether you're working on it, I decided to take a look at it myself. I cloned and built the plugin and hotloaded it into dalamud, and it seems to run without trouble. No errors in debug or anything. Obv you know your plugin better than me, but as far as I can tell, you should be able to just get it unblocked again with minimal changes.

**Comment by Guadoxiv** [comment]
by any chance are you able to share how you done it? or guide me as the game is very unplayable for me without this fix.

**Comment by Guadoxiv** [comment]
> This got disabled with the new update for compatibility with ff14v6.1 Since I couldn't find any info whether you're working on it, I decided to take a look at it myself. I cloned and built the plugin and hotloaded it into dalamud, and it seems to run without trouble. No errors in debug or anything. Obv you know your plugin better than me, but as far as I can tell, you should be able to just get it unblocked again with minimal changes.

by any chance are you able to share how you done it? or guide me as the game is very unplayable for me without this fix.

**Comment by RB2804** [comment]
> This got disabled with the new update for compatibility with ff14v6.1 Since I couldn't find any info whether you're working on it, I decided to take a look at it myself. I cloned and built the plugin and hotloaded it into dalamud, and it seems to run without trouble. No errors in debug or anything. Obv you know your plugin better than me, but as far as I can tell, you should be able to just get it unblocked again with minimal changes.

I would like to know the process for doing this too if possible, battling the game randomly eating inputs every couple of minutes is the worst!

**Comment by Nitesco-tano** [comment]
> This got disabled with the new update for compatibility with ff14v6.1 Since I couldn't find any info whether you're working on it, I decided to take a look at it myself. I cloned and built the plugin and hotloaded it into dalamud, and it seems to run without trouble. No errors in debug or anything. Obv you know your plugin better than me, but as far as I can tell, you should be able to just get it unblocked again with minimal changes.

I would love to know how you did it too.

**Comment by Sklacies** [comment]
I'm not sure if this is what they did, but you can take the downloaded DeviceChangeFix folder from the installedplugins folder and place it into the devPlugins folder. Subsequently, open DeviceChangeFix.json in the folder itself and edit the DalamudApiLevel from 5 to 6. I'm unsure if the .json thing is required but it's what worked for me.

**Comment by Taluu** [comment]
Is this all there is to do, or you need to also add the dev stuff on dalamud's settings ? As there's already a `devplugins` in the folder (which, on my drive is in `users/<name>/AppData/Roaming/XIVLauncher`).

**edit :** nevermind, it is automatically detected. Was confused with the dalamud's settings and its Q&A section.

**re-edit :** so far so good after ~20min of playing, no disconnection whatsoever. But yeah, if @PGGB could have a look on the new api6 to be sure, that'd be great (my c# knowledge is inexistant at best)

**Comment by RB2804** [comment]
Still working okay for you guys? I fear I'll have no choice but to use this method because playing without the plugin makes the game almost unplayable, but I know SE did a lot of code refactoring with 6.1 and I definitely wouldn't want to put my account at risk.

**Comment by PGGB** [comment]
I just made a pull request for the update, once it's merged you can update it ingame: https://github.com/goatcorp/DalamudPlugins/pull/2338

**Comment by PGGB** [comment]
Already merged
