### ISSUE TITLE
Update for API7

### ISSUE THREAD

**Issue by Otaku-2** [PGGB/DeviceChangeFix#6]

**Comment by NotNite** [comment]
You'll need to (at a cursory glance):
- check that your signature is up to date
- remove OutputPath, as devPlugins is deprecated
- bump DalamudPackager version
- set up the new build system (goatcorp/DalamudPluginsD17)

**Comment by PGGB** [comment]
The Plugin is currently maintained here: https://github.com/Jessidhia/DeviceChangeFix
