### ISSUE TITLE
This is a fake repository and should get the creator banned.

### ISSUE THREAD

**Issue by Moltresrider** [PGGB/DeviceChangeFix#7]
Just unknown files that Windows does not recognize, no actual Windows releases or installers. Obviously meant for Mac or Linux despite claiming to be for Windows.

No way to install this or anything.

This is a troll repository just for people Googling the issue to get their hopes up JUST to see unusable files

**Comment by wylie13-home** [comment]
This requires the quick launcher and Dalamud. Just search for the plugin there.
